#!/usr/bin/perl

$|++;

$args{$_}++ for @ARGV;

$_ = "-- echo server --\n";

print			if $args{"--stdout"};
print STDERR	if $args{"--stderr"};
exit			if @ARGV;

while (<>) {
	last if /bye/i;
	print STDERR;
	}
